image: node:6.11.2

stages:
  - build
  - test
  - deploy_sandbox
  
# 編譯封測站環境
build:
  stage: build
  image: node:argon
  only:
    - sandbox
  script:
    - \cp .env.sandbox .env
    - node -v

# 執行測試
test:
  stage: test
  only:
    - sandbox
    - master
  script:
    - npm run test
# 部屬到封測站
deploy_sandbox:
  stage: deploy_sandbox
  only:
    - sandbox
  script:
    - ssh ycuser@192.168.92.247 -p16022
    - cd ~/docker/170814-pt-game-hall-sandbox
    - git pull
    - yes | cp .env.sandbox .env
    - docker-compose restart
